<?php

namespace common\models;

/**
 * This is the model class for table "room".
 *
 * @property int $id
 * @property string|null $title
 * @property int|null $room_number
 *
 * @property Group[] $groups
 */
class Room extends \yii\db\ActiveRecord
{

    public $fullInfo;

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $this->fullInfo = $this->title  . '- qavat ' . $this->room_number . ' - xona';
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'room';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['room_number'], 'integer'],
            [['title'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Qavat',
            'room_number' => 'Room Number',
        ];
    }

    /**
     * Gets query for [[Groups]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGroups()
    {
        return $this->hasMany(Group::class, ['room_id' => 'id']);
    }
}
