<?php

namespace common\models;

/**
 * This is the model class for table "teacher".
 *
 * @property int $id
 * @property string|null $firstName
 * @property string|null $lastName
 * @property string|null $phoneNumber
 *
 * @property Group[] $groups
 */
class Teacher extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $fullName;

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $this->fullName = $this->firstName  . ' ' . $this->lastName;
    }
    public static function tableName()
    {
        return 'teacher';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['firstName', 'lastName'], 'string', 'max' => 50],
            [['phoneNumber'], 'string', 'max' => 15],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firstName' => 'First Name',
            'lastName' => 'Last Name',
            'phoneNumber' => 'Phone Number',
        ];
    }

    /**
     * Gets query for [[Groups]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGroups()
    {
        return $this->hasMany(Group::class, ['teacher_id' => 'id']);
    }
}
